name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master', ou qualquer branch que você deseja usar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: actions/configure-pages@v2
        with:
          folder: 'build'  # Diretório onde os arquivos estáticos são gerados pelo comando de build

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
